/*
 * containers.h — generic containers, the C way.
 *
 * C has no templates. There are three ways to write a container that works
 * for any type, and this header uses two of them:
 *
 *   void* + element size   one implementation, runtime size, casts at the
 *                          edges. This is what qsort does. Used for Vec.
 *   macros                 a fresh struct and functions per type, generated
 *                          textually. No casts, full type checking, larger
 *                          binary. Used for the typed Vec wrapper.
 *
 * (The third is code generation outside the language, which is a build
 * system's problem rather than C's.)
 *
 * Techniques from: about_function_pointers (vtables and comparators),
 * about_preprocessor (token pasting), about_generic (type dispatch),
 * about_dynamic_memory (growth and ownership).
 */
#ifndef KOAN_CONTAINERS_H
#define KOAN_CONTAINERS_H

#include <stddef.h>

/* ------------------------------------------------------------------ */
/* Vec — a growable array over untyped storage                         */
/* ------------------------------------------------------------------ */

typedef struct {
    unsigned char *data;
    size_t         len;       /* elements, not bytes */
    size_t         cap;
    size_t         elem_size;
} Vec;

void  vec_init(Vec *v, size_t elem_size);
void  vec_free(Vec *v);
bool  vec_push(Vec *v, const void *elem);
bool  vec_pop(Vec *v, void *out);
void *vec_at(const Vec *v, size_t i);      /* null if out of range */
bool  vec_reserve(Vec *v, size_t want);
void  vec_clear(Vec *v);

/* Sort with a comparator, exactly like qsort. */
void vec_sort(Vec *v, int (*cmp)(const void *, const void *));

/* First index whose element satisfies the predicate, or SIZE_MAX. */
size_t vec_find(const Vec *v, bool (*pred)(const void *elem, void *user),
                void *user);

/*
 * A typed wrapper generated by macro. VEC_DECLARE puts the declarations in a
 * header; VEC_DEFINE puts the definitions in exactly one .c file — the
 * one-definition rule from about_translation_units applies here too.
 *
 *     VEC_DECLARE(IntVec, int_vec, int)
 *     VEC_DEFINE(IntVec, int_vec, int)
 *
 *     IntVec v;
 *     int_vec_init(&v);
 *     int_vec_push(&v, 42);        // takes an int, not a void*
 *     int x = int_vec_at(&v, 0);   // returns an int, no cast
 */
#define VEC_DECLARE(Type, prefix, Elem)                                       \
    typedef struct { Vec inner; } Type;                                       \
    void  prefix##_init(Type *v);                                             \
    void  prefix##_free(Type *v);                                             \
    bool  prefix##_push(Type *v, Elem value);                                 \
    Elem  prefix##_at(const Type *v, size_t i);                               \
    size_t prefix##_len(const Type *v)

#define VEC_DEFINE(Type, prefix, Elem)                                        \
    void prefix##_init(Type *v)  { vec_init(&v->inner, sizeof(Elem)); }       \
    void prefix##_free(Type *v)  { vec_free(&v->inner); }                     \
    bool prefix##_push(Type *v, Elem value)                                   \
        { return vec_push(&v->inner, &value); }                               \
    Elem prefix##_at(const Type *v, size_t i)                                 \
        { return *(Elem *)vec_at(&v->inner, i); }                             \
    size_t prefix##_len(const Type *v) { return v->inner.len; }

/* ------------------------------------------------------------------ */
/* Map — a string-keyed hash table with open addressing                */
/* ------------------------------------------------------------------ */

typedef struct {
    char  *key;        /* owned; null means the slot is empty */
    void  *value;      /* not owned — the caller decides its lifetime */
    size_t hash;
} MapEntry;

typedef struct {
    MapEntry *slots;
    size_t    cap;     /* always a power of two, so masking replaces modulo */
    size_t    len;
} Map;

void  map_init(Map *m);
void  map_free(Map *m);
bool  map_put(Map *m, const char *key, void *value);
void *map_get(const Map *m, const char *key);      /* null if absent */
bool  map_has(const Map *m, const char *key);
bool  map_remove(Map *m, const char *key);

/* Walk every entry. Return false from the callback to stop early. */
void map_each(const Map *m,
              bool (*visit)(const char *key, void *value, void *user),
              void *user);

#endif /* KOAN_CONTAINERS_H */
